#!/bin/bash
# My Telegram : https://t.me/zerossl
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
# // Exporting Language to UTF-8

export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'


# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther=".wisnu"
# ==========================================
# Getting
MYIP=$(wget -qO- ipinfo.io/ip);
clear
echo -n > /tmp/other.txt
data=( `cat /etc/xray/xtrojan.json | grep '^###' | cut -d ' ' -f2`);
data=( `cat /etc/xray/xss.json | grep '^###' | cut -d ' ' -f2`);
data=( `cat /etc/xray/xvmess.json | grep '^###' | cut -d ' ' -f2`);
data=( `cat /etc/xray/xvless.json | grep '^###' | cut -d ' ' -f2`);
data=( `cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f2`);
echo -e "\033[1;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;46m 🔰 CEK USER SENYAP TAPI GANAS 🔰  \e[m"       
echo -e "\033[1;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
n=0
user=$akun
echo -e "$jum" >> /tmp/ipxray.txt
n=$((n+1))
fi
done
for user in "${data[@]}"
do
if [[ -n "$akun" ]]; then
akun="tidakada"
fi
echo -n > /tmp/ipxray.txt
data2=( `cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f3 | sed 's/tcp6://g' | cut -d ":" -f1 | sort | uniq`);
for ip in "${data2[@]}"
do
jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f3 | sed 's/tcp6://g' | cut -d ":" -f1 | grep -w "$ip" | sort | uniq)
if [[ "$jum" = "$ip" ]]; then
echo "$jum" >> /tmp/ipxray.txt
else
echo "$ip" >> /tmp/other.txt
fi
jum2=$(cat /tmp/ipxray.txt | nl)
sed -i "/$jum2/d" /tmp/other.txt > /dev/null 2>&1
done
jum=$(cat /tmp/ipxray.txt)
if [[ -n "$jum" ]]; then
jum2=$(cat /tmp/ipxray.txt | nl)
echo -e "$user :"
echo -e "$jum2"
fi
rm -f /tmp/ipxray.txt
fi
done
rm -f /tmp/other.txt
done
else
jum2=$(cat /tmp/ipxray.txt | nl)
lastlogin=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f2 | tail -1)
echo -e "${RED}VLESS WEBSOCKET"
echo -e "USER :${LIGHT} ${akun} ${NC}
${LIGHT}JAM LOGIN : ${lastlogin} WIB ${NC} ";
echo -e "$jum2";
echo -e "Total logins: $n"
echo -e "\033[1;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;46m    🔰SOLO THE SPIRIT OF JAVA🔰    \e[m"   
echo -e "\033[1;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
fi
rm -rf /tmp/ipxray.txt
done
rm -rf /tmp/other.txt

echo ""
read -n 1 -s -r -p "Ketik Bebas Untuk Ke Menu Utama"
menu
